USE [master]
GO
/****** Object:  Database [DESPRO]    Script Date: 25.06.2018 17:03:20 ******/
CREATE DATABASE [DESPRO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DESPRO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DESPRO.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DESPRO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DESPRO_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DESPRO] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DESPRO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DESPRO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DESPRO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DESPRO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DESPRO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DESPRO] SET ARITHABORT OFF 
GO
ALTER DATABASE [DESPRO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DESPRO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DESPRO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DESPRO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DESPRO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DESPRO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DESPRO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DESPRO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DESPRO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DESPRO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DESPRO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DESPRO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DESPRO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DESPRO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DESPRO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DESPRO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DESPRO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DESPRO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DESPRO] SET  MULTI_USER 
GO
ALTER DATABASE [DESPRO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DESPRO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DESPRO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DESPRO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DESPRO] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DESPRO', N'ON'
GO
ALTER DATABASE [DESPRO] SET QUERY_STORE = OFF
GO
USE [DESPRO]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [DESPRO]
GO
/****** Object:  UserDefinedFunction [dbo].[_BUL_YURUYEN_BAKIYE]    Script Date: 25.06.2018 17:03:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[_BUL_YURUYEN_BAKIYE](@INC INT, @CARI_KODU NVARCHAR(35))
RETURNS DECIMAL(28,8) 
AS
BEGIN
DECLARE @TT1 TABLE
(
	ID INT IDENTITY(1,1) NOT NULL,
	CARI_KODU NVARCHAR(35) NULL,
	BORC DECIMAL(28,8) NULL,
	ALACAK DECIMAL(28,8) NULL,
	INCKEYNO INT NULL
)
INSERT @TT1 (CARI_KODU, BORC, ALACAK, INCKEYNO)
SELECT Q1.CARI_KOD, Q1.BORC, Q1.ALACAK, Q1.ID FROM TBL_CARIHAREKET AS Q1 WHERE Q1.CARI_KOD = @CARI_KODU ORDER BY Q1.TARIH, Q1.ID

DECLARE @BAKIYE DECIMAL(28,8)
SET @BAKIYE = (SELECT SUM(BORC-ALACAK) FROM @TT1 WHERE ID <= (SELECT ID FROM @TT1 WHERE INCKEYNO = @INC))

RETURN @BAKIYE
END


GO
/****** Object:  UserDefinedFunction [dbo].[FNC_STOK_YURUYEN_BAKIYE]    Script Date: 25.06.2018 17:03:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FNC_STOK_YURUYEN_BAKIYE](@INC INT, @STOK_KODU NVARCHAR(35), @SUBE INT, @SUBELERDAHILMI CHAR(1))
RETURNS DECIMAL(28,8) 
AS
BEGIN
DECLARE @TT1 TABLE
(
	ID INT IDENTITY(1,1) NOT NULL,
	SUBE_KODU INT,
	STOK_KODU NVARCHAR(35) NULL,
	GIRMIK DECIMAL(28,8) NULL,
	CIKMIK DECIMAL(28,8) NULL,
	INCKEYNO INT NULL
)

IF @SUBELERDAHILMI = 'H'
BEGIN
INSERT @TT1 (SUBE_KODU, STOK_KODU, GIRMIK, CIKMIK, INCKEYNO)
SELECT Q1.SUBE_KOD, Q1.STOK_KODU, ISNULL(CASE WHEN Q1.GC_KOD = 'G' THEN Q1.MIKTAR END,0), ISNULL(CASE WHEN Q1.GC_KOD = 'C' THEN Q1.MIKTAR END,0), Q1.ID FROM TBL_STOKHAREKET AS Q1 WHERE Q1.STOK_KODU = @STOK_KODU AND Q1.SUBE_KOD = @SUBE ORDER BY Q1.TARIH, Q1.ID
END

ELSE
BEGIN
INSERT @TT1 (SUBE_KODU, STOK_KODU, GIRMIK, CIKMIK, INCKEYNO)
SELECT Q1.SUBE_KOD, Q1.STOK_KODU, ISNULL(CASE WHEN Q1.GC_KOD = 'G' THEN Q1.MIKTAR END,0), ISNULL(CASE WHEN Q1.GC_KOD = 'C' THEN Q1.MIKTAR END,0), Q1.ID FROM TBL_STOKHAREKET AS Q1 WHERE Q1.STOK_KODU = @STOK_KODU ORDER BY Q1.TARIH, Q1.ID
END

DECLARE @BAKIYE DECIMAL(28,8)
SET @BAKIYE = (SELECT SUM(GIRMIK - CIKMIK) FROM @TT1 WHERE ID <= (SELECT ID FROM @TT1 WHERE INCKEYNO = @INC))

RETURN @BAKIYE
END
GO
/****** Object:  UserDefinedFunction [dbo].[TRK]    Script Date: 25.06.2018 17:03:20 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE FUNCTION [dbo].[TRK](@A NVARCHAR(4000))
RETURNS NVARCHAR(4000)  
AS 
BEGIN
  DECLARE @TMP NVARCHAR(4000) 
  SET @TMP = REPLACE(@A COLLATE LATIN1_GENERAL_BIN, CHAR(208), N'Ğ')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(220), N'Ü')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(222), N'Ş')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(221), N'İ')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(214), N'Ö')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(199), N'Ç')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(73), N'I')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(240), N'ğ')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(252), N'ü')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(254), N'ş')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(105), N'i')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(246), N'ö')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(231), N'ç')
  SET @TMP = REPLACE(@TMP COLLATE LATIN1_GENERAL_BIN, CHAR(253), N'ı')
  RETURN @TMP
END
GO
/****** Object:  UserDefinedFunction [dbo].[YUVARLAMA]    Script Date: 25.06.2018 17:03:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE FUNCTION [dbo].[YUVARLAMA](@SAYI DECIMAL(28,8))
RETURNS DECIMAL(28,8)
AS 
BEGIN

DECLARE @AYRAC INT
DECLARE @TAMKISIM INT
DECLARE @ONDBAS INT
DECLARE @ONDBAS1 INT
DECLARE @ONDBAS2 INT
DECLARE @SONUC DECIMAL(28,8)
DECLARE @YENI DECIMAL(28,8) 


SET @SONUC = 0
SET @YENI = 0
SET @TAMKISIM = 0


SET @AYRAC = CHARINDEX('.',CONVERT(VARCHAR,@SAYI)) + 1
SET @TAMKISIM = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),1,@AYRAC - 1),'.','')


IF(@SAYI >= 0 AND @SAYI <10)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 1),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS1 = 9 AND @ONDBAS2 >5 )
       BEGIN
              SET @ONDBAS1 = 0
              SET @ONDBAS2 = 0
              SET @TAMKISIM = @TAMKISIM + 1
       END
       IF(@ONDBAS2 > 0 AND @ONDBAS2 <3)
       BEGIN
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS2 > 2 AND @ONDBAS2 <5)
       BEGIN
       SET @ONDBAS2 = 5
       END
       IF(@ONDBAS2 > 5 AND @ONDBAS2 < 10)
       BEGIN
       SET @ONDBAS2 = 0
       SET @ONDBAS1 = @ONDBAS1 + 1
       END
END

IF(@SAYI >= 10 AND @SAYI <50)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 2),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS > 0 AND @ONDBAS <13 )
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS > 12 AND @ONDBAS <25)
       BEGIN
       SET @ONDBAS1 = 2
       SET @ONDBAS2 = 5
       END
       IF(@ONDBAS > 25 AND @ONDBAS <35 )
       BEGIN
       SET @ONDBAS1 = 2
       SET @ONDBAS2 = 5
       END
       IF(@ONDBAS > 34 AND @ONDBAS <50 )
       BEGIN
       SET @ONDBAS1 = 5
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS > 50 AND @ONDBAS <65 )
       BEGIN
       SET @ONDBAS1 = 5
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS > 64 AND @ONDBAS <75 )
       BEGIN
       SET @ONDBAS1 = 7
       SET @ONDBAS2 = 5
       END
       IF(@ONDBAS > 75 AND @ONDBAS <85 )
       BEGIN
       SET @ONDBAS1 = 7
       SET @ONDBAS2 = 5
       END
       IF(@ONDBAS > 85 AND @ONDBAS <100 )
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END
IF(@SAYI >= 50 AND @SAYI < 100)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 2),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END

IF(@SAYI >= 100 AND @SAYI < 1000)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 3),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END


IF(@SAYI >= 1000 AND @SAYI < 10000)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 4),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END

IF(@SAYI >= 10000 AND @SAYI < 100000)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 5),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END

IF(@SAYI >= 100000 AND @SAYI < 1000000)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 6),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END

IF(@SAYI >= 1000000 AND @SAYI < 1000000)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 7),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END

IF(@SAYI >= 10000000 AND @SAYI < 10000000)

BEGIN
SET @ONDBAS = REPLACE(SUBSTRING(CONVERT(VARCHAR,@SAYI),@AYRAC,@AYRAC - 8),'.','')
SET @ONDBAS1 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),1,1))
SET @ONDBAS2 = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,@ONDBAS),2,2))
       IF(@ONDBAS >=0 AND @ONDBAS < 50)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       END
       IF(@ONDBAS >=50 AND @ONDBAS < 100)
       BEGIN
       SET @ONDBAS1 = 0
       SET @ONDBAS2 = 0
       SET @TAMKISIM = @TAMKISIM + 1
       END
END

DECLARE @O1 VARCHAR 
DECLARE @O2 VARCHAR
SET @O1 = CONVERT(varchar,@ONDBAS1)
SET @O2 = CONVERT(varchar,@ONDBAS2)

SET @YENI = CONVERT(DECIMAL(28,8),('0' + '.' + @O1 + @O2))
SET @SONUC = @YENI + @TAMKISIM

RETURN @SONUC 
END
GO
/****** Object:  Table [dbo].[TBL_CARISABIT]    Script Date: 25.06.2018 17:03:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_CARISABIT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CARI_KOD] [varchar](15) NOT NULL,
	[CARI_ISIM] [varchar](100) NOT NULL,
	[ADRES] [varchar](100) NULL,
	[IL] [varchar](30) NULL,
	[ILCE] [varchar](30) NULL,
	[TEL] [varchar](20) NULL,
	[FAKS] [varchar](20) NULL,
	[GSM] [varchar](20) NULL,
	[VERGIDAIRESI] [varchar](30) NULL,
	[VERGINUMARASI] [varchar](10) NULL,
	[TCKIMLIKNO] [varchar](11) NULL,
	[YETKILI] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[ACIKLAMA] [varchar](100) NULL,
	[CARI_TIP] [varchar](1) NOT NULL,
	[CARI_TIP2] [varchar](1) NOT NULL,
 CONSTRAINT [PK_TBL_CARISABIT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_CARIHAREKET]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_CARIHAREKET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CARI_KOD] [varchar](15) NOT NULL,
	[TARIH] [datetime] NOT NULL,
	[VADE_TARIHI] [datetime] NOT NULL,
	[BELGE_NO] [varchar](16) NOT NULL,
	[ACIKLAMA] [varchar](50) NOT NULL,
	[BORC] [decimal](28, 8) NOT NULL,
	[ALACAK] [decimal](28, 8) NOT NULL,
	[DOVIZ_TURU] [smallint] NOT NULL,
	[DOVIZ_TUTAR] [decimal](28, 8) NOT NULL,
	[HAREKET_TURU] [char](1) NOT NULL,
 CONSTRAINT [PK_TBL_CARIHAREKET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VW_CARI_HAREKET]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CARI_HAREKET] AS
SELECT
[ID] = Q1.ID,
[HARK_TARH] = Q1.HARK_TARH,
[INC] = Q1.HARK_REF1,
[CARI_KOD] = Q1.CARI_KODU,
[CARI_ISIM] = Q1.CARI_ISIM,
[HAREKET_TURU] = Q1.HAREKET_TURU,
--[HAREKET_TURU] = CASE WHEN Q1.HAREKET_TURU = 'A' THEN N'A-Devir'
--					  WHEN Q1.HAREKET_TURU = 'B' THEN N'B-Fatura' 
--					  WHEN Q1.HAREKET_TURU = 'C' THEN N'C-İade Fatura'
--					  WHEN Q1.HAREKET_TURU = 'D' THEN N'D-Kasa'
--					  WHEN Q1.HAREKET_TURU = 'E' THEN N'E-Müşteri Senetleri'
--					  WHEN Q1.HAREKET_TURU = 'F' THEN N'F-Borç Senetleri'
--					  WHEN Q1.HAREKET_TURU = 'G' THEN N'G-Müşteri Senetleri'
--					  WHEN Q1.HAREKET_TURU = 'H' THEN N'H-Borç Çekleri'
--					  WHEN Q1.HAREKET_TURU = 'I' THEN N'I-Protestolu Senet'
--					  WHEN Q1.HAREKET_TURU = 'J' THEN N'J-Karşılıksız Çek'
--					  WHEN Q1.HAREKET_TURU = 'K' THEN N'K-Dekont'
--					  WHEN Q1.HAREKET_TURU = 'L' THEN N'L-Muhtelif'
--					  END,
[BELGE_NO] = Q1.BELGE_NO,
[ACIKLAMA] = DBO.TRK(Q1.ACIKLAMA),
[VADE_TARIHI] = Q1.VADE_TARIHI,
[CARI_BORC] = Q1.CARI_BORC,
[CARI_ALCK] = Q1.CARI_ALCK,
[CARI_BAKY] = dbo._BUL_YURUYEN_BAKIYE(Q1.HARK_REF1, Q1.CARI_KODU)
FROM
(
SELECT
[ID] = Q1.ID,
[HARK_TARH] = Q1.TARIH,
[HARK_REF1] = Q1.ID,
--[HARK_REF2] = CONVERT(DECIMAL(28,0), CONVERT(NVARCHAR(10), Q1.TARIH, 112) + DBO._BUL(Q1.INC_KEY_NUMBER)),
[CARI_KODU] = Q1.CARI_KOD,
[CARI_ISIM] = Q2.CARI_ISIM,
[HAREKET_TURU] = Q1.HAREKET_TURU,
[BELGE_NO] = Q1.BELGE_NO,
[ACIKLAMA] = Q1.ACIKLAMA,
[VADE_TARIHI] = Q1.VADE_TARIHI,
[CARI_BORC] = Q1.BORC,
[CARI_ALCK] = Q1.ALACAK
FROM TBL_CARIHAREKET AS Q1 LEFT JOIN
	 TBL_CARISABIT AS Q2 ON Q2.CARI_KOD = Q1.CARI_KOD
)
AS Q1

GO
/****** Object:  Table [dbo].[TBL_FATUIRS]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_FATUIRS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FTIRSIP] [char](1) NOT NULL,
	[TIP] [char](1) NOT NULL,
	[BELGE_NO] [varchar](16) NOT NULL,
	[CARI_KOD] [varchar](15) NOT NULL,
	[TARIH] [datetime] NOT NULL,
	[VADE_TARIHI] [datetime] NOT NULL,
	[BRUT_TUTAR] [decimal](28, 8) NOT NULL,
	[SAT_ISKT] [decimal](28, 8) NOT NULL,
	[KDV] [decimal](28, 8) NOT NULL,
	[GENEL_TOPLAM] [decimal](28, 8) NOT NULL,
 CONSTRAINT [PK_TBL_FATUIRS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VW_BELGE]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_BELGE] AS
SELECT BELGE_NO, A.CARI_KOD,B.CARI_ISIM, TARIH, VADE_TARIHI,BRUT_TUTAR,SAT_ISKT,
KDV, GENEL_TOPLAM FROM [TBL_FATUIRS] A
LEFT OUTER JOIN [TBL_CARISABIT] B ON A.CARI_KOD = B.CARI_KOD
GO
/****** Object:  View [dbo].[VW_CARIRAPOR]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_CARIRAPOR] AS
SELECT A.ID, A.CARI_KOD,HARK_TARH,A.BELGE_NO,A.VADE_TARIHI,
--[ACIKLAMA] = CASE WHEN (SELECT B.STOK_ADI FROM _DSPR_TBL_STOKSABIT B LEFT OUTER JOIN _DSPR_TBL_STOKHAREKET C ON B.STOK_KODU = C.STOK_KODU
-- WHERE C.FISNO = A.BELGE_NO AND C.CARI_KOD = A.CARI_KOD) IS NULL THEN A.ACIKLAMA
-- ELSE (SELECT B.STOK_ADI FROM _DSPR_TBL_STOKSABIT B LEFT OUTER JOIN _DSPR_TBL_STOKHAREKET C ON B.STOK_KODU = C.STOK_KODU
-- WHERE C.FISNO = A.BELGE_NO AND C.CARI_KOD = A.CARI_KOD) END,

-- [MIKTAR] = CASE WHEN (SELECT D.MIKTAR FROM _DSPR_TBL_STOKHAREKET D WHERE D.FISNO = A.BELGE_NO AND D.CARI_KOD = A.CARI_KOD) IS NULL THEN '1'
-- ELSE (SELECT D.MIKTAR FROM _DSPR_TBL_STOKHAREKET D WHERE D.FISNO = A.BELGE_NO AND D.CARI_KOD = A.CARI_KOD) END,

-- [NET_FIYAT] = CASE WHEN (SELECT D.NET_FIYAT FROM _DSPR_TBL_STOKHAREKET D WHERE D.FISNO = A.BELGE_NO AND D.CARI_KOD = A.CARI_KOD) IS NULL THEN '1'
-- ELSE (SELECT D.NET_FIYAT FROM _DSPR_TBL_STOKHAREKET D WHERE D.FISNO = A.BELGE_NO AND D.CARI_KOD = A.CARI_KOD) END,

A.CARI_BORC,A.CARI_ALCK,A.CARI_BAKY,HAREKET_TURU 
FROM [dbo].[VW_CARI_HAREKET] A 

GROUP BY A.ID, A.CARI_KOD,HARK_TARH,A.BELGE_NO,A.VADE_TARIHI,A.ACIKLAMA,CARI_BORC,CARI_ALCK,CARI_BAKY,HAREKET_TURU

GO
/****** Object:  View [dbo].[VW_REHBER]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_REHBER] AS 
SELECT BELGE_NO,A.CARI_KOD,TARIH,B.CARI_ISIM
--,[CARI_ISIM] =(SELECT B.CARI_ISIM FROM [dbo].[_DSPR_TBL_CARISABIT] B WHERE A.CARI_KOD = B.CARI_KOD)
 FROM [TBL_FATUIRS] A
LEFT OUTER JOIN [TBL_CARISABIT] B ON A.CARI_KOD = B.CARI_KOD 
GO
/****** Object:  Table [dbo].[TBL_STOKSABITEK]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_STOKSABITEK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STOK_KODU] [varchar](35) NOT NULL,
	[STOK_ADI] [varchar](100) NOT NULL,
	[GRUP_KODU] [varchar](15) NULL,
	[KOD1] [varchar](15) NULL,
	[KOD2] [varchar](15) NULL,
	[KOD3] [varchar](15) NULL,
	[KOD4] [varchar](15) NULL,
	[KOD5] [varchar](15) NULL,
 CONSTRAINT [PK_TBL_STOKSABITEK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_STOKSABIT]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_STOKSABIT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STOK_KODU] [varchar](55) NOT NULL,
	[VARYASYON_KODU] [int] NOT NULL,
	[KOD_1] [varchar](50) NULL,
	[GRUP_KODU] [varchar](30) NULL,
	[ACIKLAMA] [varchar](50) NULL,
	[DEPO_KODU] [varchar](50) NULL,
	[RENK_ADET] [int] NULL,
	[RENK1] [varchar](30) NULL,
	[BOBIN1] [varchar](30) NULL,
	[RENK2] [varchar](30) NULL,
	[BOBIN2] [varchar](30) NULL,
	[RENK3] [varchar](30) NULL,
	[BOBIN3] [varchar](30) NULL,
	[RENK4] [varchar](30) NULL,
	[BOBIN4] [varchar](30) NULL,
	[RENK5] [varchar](30) NULL,
	[BOBIN5] [varchar](30) NULL,
	[RENK6] [varchar](30) NULL,
	[BOBIN6] [varchar](30) NULL,
	[RENK7] [varchar](30) NULL,
	[BOBIN7] [varchar](30) NULL,
	[RENK8] [varchar](30) NULL,
	[BOBIN8] [varchar](30) NULL,
	[RENK9] [varchar](30) NULL,
	[BOBIN9] [varchar](30) NULL,
	[RENK10] [varchar](30) NULL,
	[BOBIN10] [varchar](30) NULL,
	[VARYASYON_ACIKLAMA] [varchar](100) NULL,
 CONSTRAINT [PK_TBL_STOKSABIT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VW_STOKBILGI]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_STOKBILGI] AS
SELECT A.STOK_KODU + CONVERT(varchar, A.VARYASYON_KODU) AS KOD, A.*,
[ID2] = (SELECT B.ID FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU),
[STOK_ADI] = (SELECT B.STOK_ADI FROM TBL_STOKSABITEK B WHERE B.STOK_KODU = A.STOK_KODU),
[GRUP_KOD] = (SELECT B.GRUP_KODU FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU),
[KOD1] = (SELECT B.KOD1 FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU),
[KOD2] = (SELECT B.KOD2 FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU),
[KOD3] = (SELECT B.KOD3 FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU),
[KOD4] = (SELECT B.KOD4 FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU),
[KOD5] = (SELECT B.KOD5 FROM TBL_STOKSABITEK B WHERE A.STOK_KODU = B.STOK_KODU)
FROM TBL_STOKSABIT A
GO
/****** Object:  View [dbo].[VW_STOKKODU_KONTROL]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_STOKKODU_KONTROL] AS
SELECT STOK_KODU + CONVERT(VARCHAR(2),VARYASYON_KODU) AS STOK_KODU FROM TBL_STOKSABIT
GO
/****** Object:  View [dbo].[VW_STSABITKONTROL]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_STSABITKONTROL] AS
SELECT STOK_KODU FROM TBL_STOKSABITEK
GO
/****** Object:  Table [dbo].[TBL_STOKHAREKET]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_STOKHAREKET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STOK_KODU] [varchar](35) NOT NULL,
	[VARYASYON_KODU] [int] NOT NULL,
	[GC_KOD] [varchar](16) NOT NULL,
	[TARIH] [datetime] NOT NULL,
	[TES_TARIH] [datetime] NOT NULL,
	[FTIRSIP] [char](1) NOT NULL,
	[FISNO] [varchar](16) NOT NULL,
	[HAR_TUR] [char](1) NOT NULL,
	[SIPNO] [varchar](16) NULL,
	[IRSNO] [varchar](16) NULL,
	[ACIKLAMA] [varchar](100) NOT NULL,
	[CARI_KOD] [varchar](15) NOT NULL,
	[SUBE_KOD] [varchar](10) NOT NULL,
	[COLOR] [varchar](50) NULL,
	[SIZE] [varchar](50) NULL,
	[MIKTAR] [decimal](28, 8) NOT NULL,
	[BRUT_FIYAT] [decimal](28, 8) NOT NULL,
	[NET_FIYAT] [decimal](28, 8) NOT NULL,
	[ISK1] [decimal](28, 8) NOT NULL,
	[ISK2] [decimal](28, 8) NOT NULL,
	[ISK3] [decimal](28, 8) NOT NULL,
	[ISK4] [decimal](28, 8) NOT NULL,
	[KDV_ORAN] [decimal](28, 8) NOT NULL,
	[BELGE_TIPI] [char](1) NOT NULL,
	[SIRA] [int] NOT NULL,
 CONSTRAINT [PK_TBL_STOKHAREKET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VW_RAPOR]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_RAPOR] AS 
SELECT A.CARI_KOD, A.TARIH, A.VADE_TARIHI, BELGE_NO, B.NET_FIYAT, B.MIKTAR, BORC, ALACAK 
 FROM [dbo].[TBL_CARIHAREKET] A
LEFT OUTER JOIN [dbo].[TBL_STOKHAREKET] B ON A.CARI_KOD = B.CARI_KOD AND A.BELGE_NO = B.FISNO
GO
/****** Object:  Table [dbo].[TBL_SUBE]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_SUBE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBE_KOD] [nvarchar](50) NULL,
	[SUBE_AD] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VW_STOKDETAYRAPOR]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_STOKDETAYRAPOR] AS
SELECT A.STOK_KODU,
B.VARYASYON_ACIKLAMA,
A.COLOR,
A.SIZE,
C.SUBE_KOD,
C.SUBE_AD,
SUM(A.MIKTAR) AS MIKTAR
FROM TBL_STOKHAREKET A LEFT OUTER JOIN TBL_STOKSABIT B ON A.STOK_KODU = B.STOK_KODU LEFT OUTER JOIN TBL_SUBE C ON A.SUBE_KOD = C.SUBE_KOD
GROUP BY 
A.STOK_KODU,
A.COLOR,
A.SIZE,
B.VARYASYON_ACIKLAMA,
C.SUBE_KOD,
C.SUBE_AD
GO
/****** Object:  Table [dbo].[TBL_COLOR]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_COLOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COLOR] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_KASADETAY]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_KASADETAY](
	[ID] [int] NOT NULL,
	[KSMAS_KOD] [varchar](8) NOT NULL,
	[TARIH] [datetime] NOT NULL,
	[FISNO] [varchar](17) NULL,
	[IO] [char](1) NOT NULL,
	[TIP] [char](1) NOT NULL,
	[ACIKLAMA] [varchar](100) NULL,
	[TUTAR] [decimal](28, 8) NULL,
	[CARI_MUH] [char](1) NULL,
	[KOD] [varchar](35) NULL,
	[DOVIZTUT] [decimal](28, 8) NULL,
	[KUR] [decimal](28, 8) NULL,
	[SIRA] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_TBL_KASADETAY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_KASATANIM]    Script Date: 25.06.2018 17:03:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_KASATANIM](
	[KSMAS_KOD] [varchar](8) NOT NULL,
	[KSMAS_NAME] [varchar](50) NULL,
	[DOVIZLI] [char](1) NULL,
	[MUH_KOD] [nvarchar](35) NULL,
	[KSSONDEV_D] [datetime] NULL,
	[KSSONDEV_T] [decimal](28, 8) NULL,
	[KSMAKBUZ_BAS] [char](1) NULL,
	[KS_DEFBAS_TIP] [char](1) NULL,
	[DOVIZTIPI] [tinyint] NULL,
	[CEVRIMTIPI] [tinyint] NULL,
	[KURFARKIGELIRKODU] [nvarchar](35) NULL,
	[KURFARKIGIDERKODU] [nvarchar](35) NULL,
	[KSSONDEV_DOVIZ] [decimal](28, 8) NULL,
 CONSTRAINT [PK_TBL_KASATANIM] PRIMARY KEY CLUSTERED 
(
	[KSMAS_KOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_KULLANICI]    Script Date: 25.06.2018 17:03:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_KULLANICI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KULLANICI] [varchar](20) NOT NULL,
	[ADISOYADI] [varchar](50) NULL,
	[ADMINMI] [char](1) NOT NULL,
	[SIFRE] [varchar](20) NOT NULL,
	[EMAIL] [varchar](100) NULL,
	[GOREV] [varchar](100) NULL,
	[EMAILPASS] [nvarchar](100) NULL,
	[UNVAN] [varchar](100) NULL,
	[GSM] [varchar](20) NULL,
	[PLASIYER] [varchar](8) NULL,
 CONSTRAINT [PK_TBL_KULLANICI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[KULLANICI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_KULLANICIHAKLARI]    Script Date: 25.06.2018 17:03:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_KULLANICIHAKLARI](
	[MENUADI] [nvarchar](100) NOT NULL,
	[KULLANICI] [varchar](20) NOT NULL,
	[SIRKET] [varchar](30) NOT NULL,
	[SUBE] [smallint] NOT NULL,
	[AC] [bit] NOT NULL,
	[EKLE] [bit] NOT NULL,
	[DUZENLE] [bit] NOT NULL,
	[SIL] [bit] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_SIZE]    Script Date: 25.06.2018 17:03:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_SIZE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SIZE] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_STOKRESIM]    Script Date: 25.06.2018 17:03:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_STOKRESIM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STOK_KODU] [varchar](35) NOT NULL,
	[VARYASYON_KODU] [int] NOT NULL,
	[IMAGE1] [image] NULL,
 CONSTRAINT [PK_TBL_STOKRESIM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBL_KASADETAY] ADD  CONSTRAINT [DF_TBL_KASADETAY_TUTAR]  DEFAULT ((0)) FOR [TUTAR]
GO
ALTER TABLE [dbo].[TBL_KASADETAY] ADD  CONSTRAINT [DF_KASADETAY_DOVIZTUT]  DEFAULT ((0)) FOR [DOVIZTUT]
GO
ALTER TABLE [dbo].[TBL_KASADETAY] ADD  CONSTRAINT [DF_KASADETAY_KUR]  DEFAULT ((0)) FOR [KUR]
GO
ALTER TABLE [dbo].[TBL_KASATANIM] ADD  CONSTRAINT [DF_TBL_KASATANIM_KSSONDEV_T]  DEFAULT ((0)) FOR [KSSONDEV_T]
GO
ALTER TABLE [dbo].[TBL_KASATANIM] ADD  CONSTRAINT [DF_TBL_KASATANIM_DOVIZTIPI]  DEFAULT ((0)) FOR [DOVIZTIPI]
GO
ALTER TABLE [dbo].[TBL_KASATANIM] ADD  CONSTRAINT [DF_TBL_KASATANIM_CEVRIMTIPI]  DEFAULT ((0)) FOR [CEVRIMTIPI]
GO
ALTER TABLE [dbo].[TBL_KASATANIM] ADD  CONSTRAINT [DF_TBL_KASATANIM_KSSONDEV_DOVIZ]  DEFAULT ((0)) FOR [KSSONDEV_DOVIZ]
GO
ALTER TABLE [dbo].[TBL_KULLANICI] ADD  CONSTRAINT [DF_TBL_KULLANICI_ADMINMI]  DEFAULT ('H') FOR [ADMINMI]
GO
ALTER TABLE [dbo].[TBL_KULLANICIHAKLARI] ADD  CONSTRAINT [DF_TBL_KULLANICIHAKLARI_AC]  DEFAULT ((0)) FOR [AC]
GO
ALTER TABLE [dbo].[TBL_KULLANICIHAKLARI] ADD  CONSTRAINT [DF_TBL_KULLANICIHAKLARI_EKLE]  DEFAULT ((0)) FOR [EKLE]
GO
ALTER TABLE [dbo].[TBL_KULLANICIHAKLARI] ADD  CONSTRAINT [DF_TBL_KULLANICIHAKLARI_DUZENLE]  DEFAULT ((0)) FOR [DUZENLE]
GO
ALTER TABLE [dbo].[TBL_KULLANICIHAKLARI] ADD  CONSTRAINT [DF_TBL_KULLANICIHAKLARI_SIL]  DEFAULT ((0)) FOR [SIL]
GO
USE [master]
GO
ALTER DATABASE [DESPRO] SET  READ_WRITE 
GO
